// Este archivo define el layout raíz de la aplicación Next.js. El layout es un componente que envuelve todas las páginas de la aplicación y se utiliza para definir la estructura común, como el encabezado, pie de página o cualquier otro elemento que deba estar presente en todas las páginas. En este caso, el layout simplemente envuelve el contenido de cada página dentro de una estructura HTML básica con un elemento <html> y <body>.

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// El componente RootLayout recibe un prop children, que representa el contenido de cada página que se renderiza dentro de este layout. En este caso, simplemente se devuelve una estructura HTML básica con el contenido de cada página renderizado dentro del elemento <body>.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
